//
// Created by NandanRaj on 10-03-2026.
//
#include<iostream>
auto makeLambda_ref() {
    int temp=5;
    //Capturing local variable by reference
    return [&temp](){return temp*2;}; // contain the reference to local variable
}
auto makeLambda_copy() {
    int temp=5;
    // capturing local variable by value
    return [temp]() {
        return temp*2;
    };
}
int main() {
    auto lambda1 = makeLambda_ref();
    std::cout << "Calling lambda after temp is gone: " << lambda1() << std::endl; // Undefined behavior!
    auto lambda2=makeLambda_copy();
    std::cout<<"Calling lambda which contain copy of local temp: "<<lambda2()<<std::endl;// will work fine
    return 0;
}
// What <lambda int()> means??
// lambda  -> anonymous closure type generated by compiler
// int()   -> call operator signature
//
// So it means:
// A lambda object whose operator() returns int and takes no parameters